sudo: false

language: node_js

matrix:
  include:
    - node_js: 8
    - node_js: node
      env: COVERALLS=1

after_success:
  - if [ "x$COVERALLS" = "x1" ] && npm i coveralls; then
      nyc report --reporter=text-lcov | coveralls;
    fi
